#Penas
---
- hosts: all
  become: true
  pre_tasks:

  - name: Updating and upgrading the operating system
    package:
      update_cache: "yes"
      upgrade: "yes"
      state: latest

  - name: Fixing dpkg errors in ubuntu server
    command: dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

- hosts: Servers
  become: true
  roles:
    - "../../docker"
